startup.host: dev.lightapi.net
startup.timeout: 3000
startup.connectTimeout: 3000
startup.externalConfigDir: apps/demo-insurance-claim-mcp-server/config-cache
light-config-server-uri:

server.serviceId: com.networknt.demo.insurance-claim-mcp-1.0.0
server.environment: demo
server.ip: 0.0.0.0
server.advertisedAddress: 127.0.0.1
server.httpPort: 8087
server.enableHttp: true
server.enableHttps: false
server.enableRegistry: false
server.startOnRegistryFailure: true

portalRegistry.portalUrl: https://localhost:8438
client.verifyHostname: true
