host: ${startup.host:dev.lightapi.net}
serviceId: ${server.serviceId:com.networknt.demo.offer-decision-1.0.0}
envTag: ${server.environment:demo}
acceptHeader: application/yaml
timeout: ${startup.timeout:3000}
connectTimeout: ${startup.connectTimeout:3000}
configServerUri: ${light-config-server-uri}
authorization: ${light_portal_authorization:}
bootstrapCaCertPath: ${startup.bootstrapCaCertPath:}
externalConfigDir: ${startup.externalConfigDir:apps/demo-offer-decision-api/config-cache}
