*
!light-example-rs/
!light-example-rs/**
!light-fabric/
!light-fabric/**

light-example-rs/.git
light-example-rs/.gitnexus
light-example-rs/.claude
light-example-rs/target
light-example-rs/dist
light-example-rs/**/config-cache

light-fabric/.git
light-fabric/.gitnexus
light-fabric/target
light-fabric/docs/book
light-fabric/apps/*/config-cache
